### PR TITLE
[JENKINS-32944] use onblur instead of onchange

### PR DESCRIPTION
**Pull request by bebehei**

### CODE REVIEW

**Comment by wilmardo** [comment]
Any update on this? Why isn't this merged already?

**Comment by bebehei** [comment]
Well, finally something is going on in this PR. 🎉 

But:
- I personally dropped jenkins in my toolbox
- I've thrown out my development environment already
- The knowledge of the details faded away.

I only know, that there are some problems while creating a new Virtual Machine.

On the website, you have two fields, the first for the hypervisor, the second one for the actual VM. The list of VMs does not get updated, if there is only one hypervisor available.

> 1st commit nothing todo with onblur instead of onchange, please use separate pr but also explain why this selection setting is bad, when cloud seelction changes.

I'm pretty sure this is a prerequisite to make the 2nd commit working.

> 2nd and 3rd commit only leave the onblur change don't set value= as this is redundant, is it not?
stash 2nd and 3rd into a single commit please

i guess this might be neccessary. i don't know the details anymore. Sorry.

@g-k-r I'm not setting up an IntelliJ workspace again to make this work and test it again. Could you please do the neccessary changes to the PR?

**Comment by bebehei** [comment]
> On the website, you have two fields, the first for the hypervisor, the second one for the actual VM. The list of VMs does not get updated, if there is only one hypervisor available.

... because onchange only acts, if there are two hypervisors available. Then if you want to select the first hypervisor, you have to select the second and then the first again to have the list of virtual machines updated.

**Comment by bebehei** [comment]
> ... because onchange only acts, if there are two hypervisors available. Then if you want to select the first hypervisor, you have to select the second and then the first again to have the list of virtual machines updated.

and onblur changes on time when your focus hits the virtual machine select-field.

**Comment by bebehei** [comment]
> > 2nd and 3rd commit only leave the onblur change don't set value= as this is redundant, is it not? stash 2nd and 3rd into a single commit please
> i guess this might be neccessary. i don't know the details anymore. Sorry.

Now, I start remembering the details. The third commit fixes the same problem but now in combination with the virtual machine and its snapshot. If you have only one VM on your hypervisor annd the VM has multiple snapshots, you can't select a snapshot.

IIRC: The value has to be set (this is not redundant). If you would not set the value, by every onblur, your details in the lower layers would be dropped. (here: clicking on the VM-field and clicking somewhere else would set the snapshot-value to *empty*.

**Comment by bebehei** [comment]
Same as in #13, I'm not using Jenkins anymore. I'm closing it. If some of you want to rebase the code, feel free to do so.

**Comment by bebehei** [comment]
@bgermann Thanks for resolving the actual issue and merging! :+1: Finally after 4 years, it seems to be resolved. :muscle:

**Pull request closed without merging**
